const products = [
    {
        '_id': '1',
        'name': 'Black tree ornament',
        'image': '/images/blackOrnament.jpg',
        'description': 'Handcrafted Blown Glass Yule ornament with bow',
        'craftsman': 'M.West',
        'category': 'Ornaments',
        'price': 24.95,
        'countInStock': 4,
        'rating': 4.5,
        'numReviews': 7,
    },
    {
        '_id': '2',
        'name': 'Bermuda beach tree ornament',
        'image': '/images/ornament2.jpg',
        'description': 'Handcrafted Blown Glass Yule ornament with bow',
        'craftsman': 'M.West',
        'category': 'Ornaments',
        'price': 24.95,
        'countInStock': 2,
        'rating': 4.8,
        'numReviews': 5,
    },
    {
        '_id': '3',
        'name': 'Forest tree ornament',
        'image': '/images/ornaments.jpg',
        'description': 'Handcrafted Blown Glass Yule ornament with bow',
        'craftsman': 'M.West',
        'category': 'Ornaments',
        'price': 20.95,
        'countInStock': 14,
        'rating': 4.7,
        'numReviews': 27,
    },
    {
        '_id': '4',
        'name': 'Blue ball tree ornament',
        'image': '/images/ornaments1.jpg',
        'description': 'Handcrafted Blown Glass Yule ornament with bow',
        'craftsman': 'M.West',
        'category': 'Ornaments',
        'price': 22.95,
        'countInStock': 4,
        'rating': 2.5,
        'numReviews': 7,
    },
    {
        '_id': '5',
        'name': 'white tree ornament',
        'image': '/images/whiteOrnament.jpg',
        'description': 'Handcrafted Blown Glass Yule ornament with bow',
        'craftsman': 'M.West',
        'category': 'Ornaments',
        'price': 25.95,
        'countInStock': 23,
        'rating': 4.9,
        'numReviews': 17,
    },
    {
        '_id': '6',
        'name': 'White bubbler',
        'image': '/images/bubbler.jpg',
        'description': 'Handcrafted white bubbler for your medicinals',
        'craftsman': 'M.West',
        'category': 'Paraphenalia',
        'price': 44.95,
        'countInStock': 2,
        'rating': 4.5,
        'numReviews': 3,
    },
    {
        '_id': '7',
        'name': 'Pair of awesome pieces',
        'image': '/images/matchingPieces.jpg',
        'description': 'designer set of psychedelic smoking utensils',
        'craftsman': 'M.West',
        'category': 'Paraphenalia',
        'price': 33.95,
        'countInStock': 4,
        'rating': 4.5,
        'numReviews': 7,
    },
    {
        '_id': '8',
        'name': 'regular small pipe',
        'image': '/images/paraphenalia.jpg',
        'description': 'Handcrafted pipes for sativa or indica',
        'craftsman': 'M.West',
        'category': 'Paraphenalia',
        'price': 14.95,
        'countInStock': 42,
        'rating': 4.5,
        'numReviews': 7,
    },
    {
        '_id': '9',
        'name': 'white and yello aparatus',
        'image': '/images/pipe.jpg',
        'description': 'Handcrafted pipe',
        'craftsman': 'M.West',
        'category': 'Paraphenalia',
        'price': 14.95,
        'countInStock': 2,
        'rating': 4.5,
        'numReviews': 8,
    },
    {
        '_id': '10',
        'name': 'Sherlock',
        'image': '/images/sherlock.jpg',
        'description': 'indumanibly Mr Holmes',
        'craftsman': 'M.West',
        'category': 'Paraphenalia',
        'price': 24.95,
        'countInStock': 4,
        'rating': 4.5,
        'numReviews': 7,
    },
    {
        '_id': '11',
        'name': 'A couple marbles',
        'image': '/images/marbles2.jpg',
        'description': 'I think these are the ones you lost',
        'craftsman': 'M.West',
        'category': 'Marbles',
        'price': 4.95,
        'countInStock': 4,
        'rating': 4.5,
        'numReviews': 7,
    },
    {
        '_id': '12',
        'name': 'Some more old fashioned new stuff',
        'image': '/images/marbles3.jpg',
        'description': 'Handcrafted marbles straight from the dunce cap',
        'craftsman': 'M.West',
        'category': 'Marbles',
        'price': 9.95,
        'countInStock': 4,
        'rating': 4.5,
        'numReviews': 7,
    },
    {
        '_id': '13',
        'name': 'Standing Terrarium',
        'image': '/images/standingTerrarium.jpg',
        'description': 'Handcrafted Blown Glass standing terrarium',
        'craftsman': 'M.West',
        'category': 'Decorations',
        'price': 24.95,
        'countInStock': 4,
        'rating': 4.5,
        'numReviews': 7,
    },
    {
        '_id': '14',
        'name': 'Terrarium tree ornament',
        'image': '/images/terrarium2.jpg',
        'description': 'Handcrafted Blown Glass Yule ornament terrarium',
        'craftsman': 'M.West',
        'category': 'Decorations',
        'price': 24.95,
        'countInStock': 4,
        'rating': 4.5,
        'numReviews': 7,
    },
]

export default products;